---
kind: pipeline
name: Build

platform:
  os: linux
  arch: amd64

steps:

- name: code-format
  pull: never
  image: patwie/lint:latest
  commands:
  - run-clang-format --clang-format-executable /usr/local/bin/clang-format11 -r iot-restful-api/embedded --style Google
  - run-clang-format --clang-format-executable /usr/local/bin/clang-format11 -r traffic-light/embedded --style Google

- name: code-lint
  pull: never
  image: patwie/lint:latest
  commands:
  - 'cpplint --extensions=h,hpp,c,cpp,cc,cu,hh,ipp --filter="-build/include_order,-runtime/int,-legal/copyright" --recursive iot-restful-api/embedded > reviewdog -efm="%f:%l: %m" -name="cpplint" -reporter="local"'
  - 'cpplint --extensions=h,hpp,c,cpp,cc,cu,hh,ipp --filter="-build/include_order,-runtime/int,-legal/copyright" --recursive traffic-light/embedded > reviewdog -efm="%f:%l: %m" -name="cpplint" -reporter="local"'

- name: build
  pull: never
  image: patwie/platformio:latest
  commands:
  - 'cd /drone/src && cd iot-restful-api/embedded/iot-restful-api && platformio run -e esp12e'
  - 'cd /drone/src && cd traffic-light/embedded/traffic-light && platformio run -e esp12e'

---
kind: signature
hmac: 3e236af52a268a1b49d3b5389eddfb295d13302dc455a2d947f4cbde1b2568ee

...
